# … top of workflow unchanged …

steps:
  - uses: actions/checkout@v3

  - name: Build (and optionally push)
    run: |
      $repoRoot   = '${{ github.workspace }}'
      $workingDir = if ($Env:IN_WD  -eq 'github_workspace') { $repoRoot } else { Join-Path $repoRoot $Env:IN_WD  }
      $context    = if ($Env:IN_CTX -eq 'github_workspace') { $repoRoot } else { Join-Path $repoRoot $Env:IN_CTX }

      # -------------------------------
      # Call Run-Docker.ps1 via splat
      # -------------------------------
      $args = @{
        WorkingDirectory = $workingDir
        BuildContext     = $context
        DockerFileName   = $Env:IN_DF
        DockerImageName  = $Env:IN_IMG
        RegistryUrl      = 'ghcr.io'
        RegistryUsername = '${{ github.actor }}'
        RegistryPassword = '${{ secrets.GITHUB_TOKEN }}'
        ImageOrg         = $Env:IN_ORG
        PushDockerImage  = $Env:IN_PUSH
        DebugMode        = $Env:IN_DBG
      }

      ./Run-Docker.ps1 @args
